---
title: "Lake Powell Calculation Tool"
output: html_document
runtime: shiny
date: "2026-07-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

source("HelperFunctions/ProjectPowell.R")
library("rhandsontable")

#rsconnect::showLogs()

```
```{r Projection Calculation, echo=FALSE, warning=FALSE, message=FALSE}

# Sets up table inputs
additional_flow <- data.frame(
  Parameter = c("Additional Inflow to Lake Powell (MAF)", "Length of Addtional Inflow Period (months)"),
  stage_1 = c(0, 0), 
  stage_2 = c(0, 0),
  stage_3 = c(0, 0),
  check.names = FALSE
)

release <- data.frame(
  Parameter = c("Release Flow from Lake Powell (MAF/yr)", "Length of Release Stage (months)"),
  stage_1 = c(0,0),
  stage_2 = c(0,0),
  stage_3 = c(0,0),
  check.names = FALSE
)

output$additional_flow <- renderRHandsontable({
    rhandsontable(additional_flow)%>%
    hot_col("Parameter", readOnly = TRUE)
  })

output$release <- renderRHandsontable({
    rhandsontable(release)%>%
    hot_col("Parameter", readOnly = TRUE)
})


input_flow <- reactive({
  req(input$additional_flow)
  hot_to_r(input$additional_flow)
})

input_release <- reactive({
  req(input$release)
  hot_to_r(input$release)
})


key_elev_df <- reactive({
  # Use inputs if available, else use default values (3500 and 3490)
  if (is.null(input$buffer_elevation) || input$buffer_elevation == ""){
    buffer_elev <- data.frame(elevation = 3500, label = "Final EIS Critical Elevation: 3500 ft")
  }else{
    buffer_elev <- data.frame(elevation = as.numeric(input$buffer_elevation), label = paste0(input$buffer_elevation, " ft."))
  }
  
  if (is.null(input$catastrophic_elevation)|| input$catastrophic_elevation == "" ){
    catastrophic_elev <- data.frame(elevation = 3490, label = "Top of Penstocks: 3490 ft.")
  }else{
    catastrophic_elev <- data.frame(elevation = as.numeric(input$catastrophic_elevation), label = paste0(input$catastrophic_elevation, " ft."))
  }
  
  rbind(buffer_elev, catastrophic_elev)
})


# Passes inputs through projection function 
projection_calculated <- reactive({
  # Insures that there are proper inputs
  tbl <- rbind(input_flow(), input_release())

  add_release <-as.numeric(tbl[1,-1])#[row 1, every column but 1]
  add_time <- as.numeric(tbl[2,-1])
  release <- as.numeric(tbl[3,-1])
  release_time <- as.numeric(tbl[4, -1])
  
  req(length(add_release) > 0, !all(is.na(add_release)))
  req(length(add_time) > 0, !all(is.na(add_time)))
  req(length(release) > 0, !all(is.na(release)))
  req(length(release_time) > 0, !all(is.na(release_time)))
  
  result <- ProjectPowell(
    Inflow = "CRMMS",
    Release = release,
    Release_Time = release_time,
    Add_Release = add_release, 
    Add_Time = add_time,
    Duration = 36,
    Storage_Data = hydrodata
  )
  # Checks if crashed
  if (identical(result, "crashed")) {
    showModal(
      modalDialog(
        title = "Empty!",
        "One or more of your projections results in a negative active storage in Lake Powell.",
        easyClose = TRUE,
        footer = modalButton("OK")
      )
    )

    return(NULL)
  }

  result
})

output$inflow_date_ranges <- renderText({
  add_time <- unlist(input_flow()[2,-1])
  result_list<- fCalculateDateRange(add_time, "Additional Inflow")
  
  HTML(
    paste(
      unlist(na.omit(result_list)),
      collapse = "<br>"
    )
  )
})

output$release_date_ranges <- renderText({
  release_time <- unlist(input_release()[2,-1])
  result_list<- fCalculateDateRange(release_time, "Release")
  
  HTML(
    paste(
      unlist(na.omit(result_list)),
      collapse = "<br>"
    )
  )
})

# Adds 24 MS plot to projection
CRMMS_projection <- fAutoReadCRMMS24MS("Lake Powell", "Pool Elevation")
CRMMS_filtered <- data.frame(datetime = CRMMS_projection$date, storage = NA, elevation = CRMMS_projection$`24MS MIN PROB`,inflow = NA, outflow = NA, label = "24MS MIN PROB" )

# Displays 24 MS if toggled True
projection <- reactive({

  if (isTRUE(input$CRMMS_input)) {
    rbind(projection_calculated(), CRMMS_filtered)
  } else {
    projection_calculated()
  }

})

# plots projection
output$projectionplot <- renderPlot({
  fplotprojection(projection(), key_elev_df())
})


# Annual Tables 
inflow_no_add_table <- reactive({fAnnualValues(projection()[projection()$label == "No Additional Release",], "inflow", hydrodata) })

inflow_add_table <- reactive({fAnnualValues(projection()%>%
        dplyr::filter(!label %in% 
            c("No Additional   Release", "24MS MIN PROB")), "inflow", hydrodata)})

inflow_table <- reactive({
  data.frame(
    `Inflow Volume Without Additional Flow (MAF)` =
      inflow_no_add_table()[["Inflow Volume (MAF)"]],
    
    `Inflow Volume With Additional Flow (MAF)` =
      inflow_add_table()[["Inflow Volume (MAF)"]],
    
    water_year =
      inflow_add_table()[["water_year"]],
    
    check.names = FALSE
  )
})

release_table <- reactive({fAnnualValues(projection()[projection()$label == "No Additional Release",], "outflow", hydrodata)})

annual_table <- reactive({merge(inflow_table(), release_table(), by = "water_year")})
  
output$annualTable <- renderTable({
  annual_table()[
    annual_table()$water_year %in% c(2025, 2026, 2027),
  ]
}, digits = 1)


```
```{r output, results = "show"}
# Inputs
rHandsontableOutput("additional_flow")
uiOutput("inflow_date_ranges")

rHandsontableOutput("release")
uiOutput("release_date_ranges")

textInput("buffer_elevation", "Buffer Elevation (ft)")
textInput("catastrophic_elevation", "Catastrophic Elevation (ft)")

checkboxInput("CRMMS_input", "Display CRMMS 24 MS MIN PROB Elevation Projection?", value = FALSE)

#Outputs
plotOutput("projectionplot")
tableOutput("annualTable")

```
